/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ipsPatcherDialog (void)
{
  GtkWidget *ipsPatcherDialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *romLabel;
  GtkWidget *patchLabel;
  GtkWidget *romfilechooserbutton;
  GtkWidget *patchfilechooserbutton;
  GtkWidget *dialog_action_area1;
  GtkWidget *button1;
  GtkWidget *button2;

  ipsPatcherDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (ipsPatcherDialog), _("IPS patcher"));
  gtk_window_set_resizable (GTK_WINDOW (ipsPatcherDialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (ipsPatcherDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (ipsPatcherDialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 4);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 4);

  romLabel = gtk_label_new (_("Rom"));
  gtk_widget_show (romLabel);
  gtk_table_attach (GTK_TABLE (table1), romLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (romLabel), 0, 0.5);

  patchLabel = gtk_label_new (_("Patch"));
  gtk_widget_show (patchLabel);
  gtk_table_attach (GTK_TABLE (table1), patchLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (patchLabel), 0, 0.5);

  romfilechooserbutton = gtk_file_chooser_button_new (_("S\303\251lectionner un fichier"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (romfilechooserbutton);
  gtk_table_attach (GTK_TABLE (table1), romfilechooserbutton, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  patchfilechooserbutton = gtk_file_chooser_button_new (_("S\303\251lectionner un fichier"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (patchfilechooserbutton);
  gtk_table_attach (GTK_TABLE (table1), patchfilechooserbutton, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  dialog_action_area1 = GTK_DIALOG (ipsPatcherDialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button1);
  gtk_dialog_add_action_widget (GTK_DIALOG (ipsPatcherDialog), button1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (ipsPatcherDialog), button2, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ipsPatcherDialog, "close",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) ipsPatcherDialog, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect_swapped ((gpointer) button2, "clicked",
                            G_CALLBACK (on_apply),
                            GTK_OBJECT (ipsPatcherDialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ipsPatcherDialog, ipsPatcherDialog, "ipsPatcherDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (ipsPatcherDialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (ipsPatcherDialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (ipsPatcherDialog, romLabel, "romLabel");
  GLADE_HOOKUP_OBJECT (ipsPatcherDialog, patchLabel, "patchLabel");
  GLADE_HOOKUP_OBJECT (ipsPatcherDialog, romfilechooserbutton, "romfilechooserbutton");
  GLADE_HOOKUP_OBJECT (ipsPatcherDialog, patchfilechooserbutton, "patchfilechooserbutton");
  GLADE_HOOKUP_OBJECT_NO_REF (ipsPatcherDialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (ipsPatcherDialog, button1, "button1");
  GLADE_HOOKUP_OBJECT (ipsPatcherDialog, button2, "button2");

  return ipsPatcherDialog;
}

GtkWidget*
create_errorDialog (void)
{
  GtkWidget *errorDialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *scrolledwindow1;
  GtkWidget *errorMessageView;
  GtkWidget *dialog_action_area2;
  GtkWidget *button3;

  errorDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (errorDialog), _("Error!"));
  gtk_window_set_resizable (GTK_WINDOW (errorDialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (errorDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (errorDialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  errorMessageView = gtk_text_view_new ();
  gtk_widget_show (errorMessageView);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), errorMessageView);
  gtk_widget_set_size_request (errorMessageView, 320, 256);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (errorMessageView), FALSE);

  dialog_action_area2 = GTK_DIALOG (errorDialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  button3 = gtk_button_new_from_stock ("gtk-dialog-error");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (errorDialog), button3, 0);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) errorDialog, "close",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (errorDialog));
  g_signal_connect_swapped ((gpointer) button3, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (errorDialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (errorDialog, errorDialog, "errorDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (errorDialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (errorDialog, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (errorDialog, errorMessageView, "errorMessageView");
  GLADE_HOOKUP_OBJECT_NO_REF (errorDialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (errorDialog, button3, "button3");

  return errorDialog;
}

GtkWidget*
create_doneDialog (void)
{
  GtkWidget *doneDialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *label3;
  GtkWidget *dialog_action_area3;
  GtkWidget *closebutton1;

  doneDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (doneDialog), _("IPS patcher"));
  gtk_window_set_resizable (GTK_WINDOW (doneDialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (doneDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (doneDialog)->vbox;
  gtk_widget_show (dialog_vbox3);

  label3 = gtk_label_new (_("Rom succesfully patched!"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), label3, FALSE, FALSE, 0);

  dialog_action_area3 = GTK_DIALOG (doneDialog)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (doneDialog), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) doneDialog, "close",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (doneDialog));
  g_signal_connect_swapped ((gpointer) closebutton1, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (doneDialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (doneDialog, doneDialog, "doneDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (doneDialog, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (doneDialog, label3, "label3");
  GLADE_HOOKUP_OBJECT_NO_REF (doneDialog, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (doneDialog, closebutton1, "closebutton1");

  return doneDialog;
}

