/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <glib.h>
#include <pthread.h>
#include <gtk/gtk.h>

#include "contrib/ips.h"

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  struct IPSPatch patch;
  GtkWidget *ipsPatcherDialog;
    
  /* Reset patch */  
  IPSReset(&patch);
  
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif
  /* Initialize GDK threads */
  g_thread_init (NULL);
  gdk_threads_init ();
  gdk_threads_enter ();
  
  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ipsPatcherDialog = create_ipsPatcherDialog ();
  /* Attach patch to the main dialog */
  g_object_set_data( G_OBJECT(ipsPatcherDialog), "patch", &patch );
  gtk_widget_show (ipsPatcherDialog);

  gtk_main ();
  
  /* Clean up everything */
  IPSClose(&patch);
  
  gdk_threads_leave ();
  	
  return 0;
}

